version: '3'

services:
    database:
        image: postgres:12.1
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: app
        volumes:
            - database_data:/var/lib/postgresql/data

    mailcatcher:
        image: schickling/mailcatcher

volumes:
    database_data:
        driver: local
